In [51]:
import torch

from model import *

In [52]:
enc = Encoder(3, 16, 2)

In [53]:
dummy = torch.empty((1, 3, 28, 28))

In [4]:
import torch

l = torch.nn.AdaptiveAvgPool2d((1, 1))
dummy = torch.empty((1, 3, 28, 28))
l(dummy).shape

torch.Size([1, 3, 1, 1])

In [54]:
m, v = enc(dummy)

torch.Size([1, 3, 28, 28])
torch.Size([1, 8, 14, 14])
torch.Size([1, 16, 7, 7])
torch.Size([1, 2, 2, 2])


In [ ]:
enc = 
dec = Decoder()

In [55]:
m.shape

torch.Size([1, 2, 2, 2])

In [56]:
l = nn.AdaptiveAvgPool2d(1)
l(m).shape

torch.Size([1, 2, 1, 1])

In [57]:
dec = Decoder(2, 16, 3)
l = nn.AdaptiveAvgPool2d(1)

In [58]:
m, v = l(m), l(v)

In [59]:
m.shape

torch.Size([1, 2, 1, 1])

In [60]:
# b = torch.nn.UpsamplingBilinear2d(2)

In [61]:
# m = b(m)
# m.shape

In [62]:
y = dec(m)

torch.Size([1, 2, 1, 1])
torch.Size([1, 8, 1, 1])
torch.Size([1, 16, 1, 1])
torch.Size([1, 16, 1, 1])
torch.Size([1, 3, 1, 1])


In [63]:
import numpy as np


i = np.linspace(-1, 1, 28)
j = np.linspace(-1, 1, 28)
index = np.transpose(np.expand_dims(np.array(np.meshgrid(i, j)), axis=0), (0, 1, 3, 2))

In [64]:
index[:, :, 0, 0]

array([[-1., -1.]])

In [65]:
index_torch = torch.tensor(index)

In [66]:
index_torch

tensor([[[[-1.0000, -1.0000, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
          [-0.9259, -0.9259, -0.9259,  ..., -0.9259, -0.9259, -0.9259],
          [-0.8519, -0.8519, -0.8519,  ..., -0.8519, -0.8519, -0.8519],
          ...,
          [ 0.8519,  0.8519,  0.8519,  ...,  0.8519,  0.8519,  0.8519],
          [ 0.9259,  0.9259,  0.9259,  ...,  0.9259,  0.9259,  0.9259],
          [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000]],

         [[-1.0000, -0.9259, -0.8519,  ...,  0.8519,  0.9259,  1.0000],
          [-1.0000, -0.9259, -0.8519,  ...,  0.8519,  0.9259,  1.0000],
          [-1.0000, -0.9259, -0.8519,  ...,  0.8519,  0.9259,  1.0000],
          ...,
          [-1.0000, -0.9259, -0.8519,  ...,  0.8519,  0.9259,  1.0000],
          [-1.0000, -0.9259, -0.8519,  ...,  0.8519,  0.9259,  1.0000],
          [-1.0000, -0.9259, -0.8519,  ...,  0.8519,  0.9259,  1.0000]]]],
       dtype=torch.float64)

In [67]:
m.shape

torch.Size([1, 2, 1, 1])

In [68]:
index_torch.shape

torch.Size([1, 2, 28, 28])

In [72]:
m_exp = torch.broadcast_to(m, (1, 2, 28, 28))
m_exp

tensor([[[[-1.7639e+33, -1.7639e+33, -1.7639e+33,  ..., -1.7639e+33,
           -1.7639e+33, -1.7639e+33],
          [-1.7639e+33, -1.7639e+33, -1.7639e+33,  ..., -1.7639e+33,
           -1.7639e+33, -1.7639e+33],
          [-1.7639e+33, -1.7639e+33, -1.7639e+33,  ..., -1.7639e+33,
           -1.7639e+33, -1.7639e+33],
          ...,
          [-1.7639e+33, -1.7639e+33, -1.7639e+33,  ..., -1.7639e+33,
           -1.7639e+33, -1.7639e+33],
          [-1.7639e+33, -1.7639e+33, -1.7639e+33,  ..., -1.7639e+33,
           -1.7639e+33, -1.7639e+33],
          [-1.7639e+33, -1.7639e+33, -1.7639e+33,  ..., -1.7639e+33,
           -1.7639e+33, -1.7639e+33]],

         [[-3.3334e+32, -3.3334e+32, -3.3334e+32,  ..., -3.3334e+32,
           -3.3334e+32, -3.3334e+32],
          [-3.3334e+32, -3.3334e+32, -3.3334e+32,  ..., -3.3334e+32,
           -3.3334e+32, -3.3334e+32],
          [-3.3334e+32, -3.3334e+32, -3.3334e+32,  ..., -3.3334e+32,
           -3.3334e+32, -3.3334e+32],
          ...,
     

In [74]:
inputs = torch.concat((m_exp, index_torch), dim=1)
inputs.shape

torch.Size([1, 4, 28, 28])